// "use client"
import './globals.css'
import { Inter } from 'next/font/google';
import Navbar from "./components/Navbar";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script></head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}


// 'use client'
// import './globals.css'
// import { Inter } from 'next/font/google'
// import Navbar from './components/Navbar'
// import Footer from './components/Footer'
// import injectContext from './context/appContext'
// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Template',
//   description: 'ecomers site template full stack',
// }

// function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Navbar />
//           {children}
//         <Footer />
//       </body>
//     </html>
//   )
// }
// export default injectContext(RootLayout)